name: バグ報告 (日本語)
description: クラッシュを除くバグの報告
#labels: [ "", "" ]
body:
  - type: input
    id: version
    attributes:
      label: RagiMaterialsのバージョン
      description: クラッシュが発生した時にプレイしていたRagiMaterialsのバージョンを記入してください。バージョンはmodsフォルダ内のjarファイルか，ゲーム内の「mods」オプションから探せます.
      placeholder: "例: v0.5.0b"
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: プレイしていたmodpack
      description: クラッシュが発生した時にプレイしていたmodpackの名前とバージョンを記入してください (modpackで遊んでいない場合は空欄)。
      placeholder: "例: "
    validations:
      required: false
  - type: input
    id: is_client
    attributes:
      label: サーバー/クライアント
      description: サーバー側 (マルチプレイ) かクライアント側 (シングルプレイ) のどちらかでクラッシュが発生したか記入してください。
      placeholder: "例: クライアント側"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: クラッシュの再現方法
      description: そのクラッシュを再現する方法を**段階ごとに**記入してください。
      placeholder: "例: (1) まず...をします。"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 本来の挙動
      description: 本来の挙動を記入してください。スクリーンショットを添付することも可能です。
      placeholder: "例: 装置Aを用いてアイテムBからアイテムCが生産される。"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の挙動
      description: 実際に起こったことを記入してください。スクリーンショットを添付することも可能です。
      placeholder: "例: 装置Aを用いたがアイテムBからアイテムCが生産されなかった。"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 追加の説明
      description: その他伝えたいことはこちらに記入してください。
      placeholder: "例: "
    validations:
      required: false
  - type: markdown
    attributes:
      value: ご報告ありがとうございます!